### ISSUE TITLE
cannot load checkpoint

### ISSUE THREAD

**Issue by l0stpenguin** [princeton-vl/DeepV2D#13]
I tried the demo
`python3 demos/demo_uncalibrated.py --video=data/demos/golf.mov`
but it crashed:
```
tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key stereo/BatchNorm/moving_stddev not found in checkpoint
Traceback (most recent call last):
  File "/Users/l0stpenguin/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/Users/l0stpenguin/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/Users/l0stpenguin/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key stereo/BatchNorm/moving_stddev not found in checkpoint
         [[{{node save/RestoreV2}}]]
```
I do not have gpu machine. Is it possible to run it without gpu?

**Comment by sconlyshootery** [comment]
I have the same problem

**Comment by sconlyshootery** [comment]
It seems like the problem is caused by different version of tensorflow, you can install tf 1.13.1 if you have cuda 10.0 or tf 12.0 if you have cuda 9.0.

**Comment by Shurik-old** [comment]
The problem is that the checkpoint stores variables for BatchNormalization like this, for example:

stereo/encoder/BatchNorm_6/beta (DT_FLOAT) [32]  
stereo/encoder/BatchNorm_6/gamma (DT_FLOAT) [32]  
stereo/encoder/BatchNorm_6/moving_mean (DT_FLOAT) [32]  
stereo/encoder/BatchNorm_6/moving_variance (DT_FLOAT) [32]  
stereo/encoder/BatchNorm_6/renorm_mean (DT_FLOAT) [32]  
stereo/encoder/BatchNorm_6/renorm_mean_weight (DT_FLOAT) []  
stereo/encoder/BatchNorm_6/renorm_stddev (DT_FLOAT) [32]  
stereo/encoder/BatchNorm_6/renorm_stddev_weight (DT_FLOAT) []

It does not contain the variable **moving_stdev**
And when creating the Depth network in code, for example:

```python
        with tf.variable_scope("encoder") as sc:
            with slim.arg_scope([slim.batch_norm], **self.batch_norm_params):
                with slim.arg_scope([slim.conv2d],
                                    weights_regularizer=slim.l2_regularizer(0.00005),
                                    normalizer_fn=None,
                                    activation_fn=None,
                                    reuse=reuse):

                    net = slim.conv2d(inputs, 32, [7, 7], stride=2)
...
```
are being created variables:

'stereo/encoder/BatchNorm_6/gamma': <tf.Variable 'stereo/encoder/BatchNorm_6/gamma:0' shape=(32,) dtype=float32_ref>, 'stereo/encoder/BatchNorm_6/beta': <tf.Variable 'stereo/encoder/BatchNorm_6/beta:0' shape=(32,) dtype=float32_ref>, 'stereo/encoder/BatchNorm_6/moving_mean': <tf.Variable 'stereo/encoder/BatchNorm_6/moving_mean:0' shape=(32,) dtype=float32_ref>,  
'stereo/encoder/BatchNorm_6/moving_variance': <tf.Variable 'stereo/encoder/BatchNorm_6/moving_variance:0' shape=(32,) dtype=float32_ref>,  
'stereo/encoder/BatchNorm_6/moving_stddev': <tf.Variable 'stereo/encoder/BatchNorm_6/**moving_stddev**:0' shape=(32,) dtype=float32_ref>,  
'stereo/encoder/BatchNorm_6/renorm_mean': <tf.Variable 'stereo/encoder/BatchNorm_6/renorm_mean:0' shape=(32,) dtype=float32_ref>,  
'stereo/encoder/BatchNorm_6/renorm_stddev': <tf.Variable 'stereo/encoder/BatchNorm_6/renorm_stddev:0' shape=(32,) dtype=float32_ref>,

Of course, Saver can't subtract what's not in the checkpoint and crashes with an error.
Apparently, the checkpoint is posted for another version of the Depth network hosted on GitHub
I tried to load the checkpoint on tw versions 1.13.1, 1.15.0. unsuccessfully.

**Comment by Shurik-old** [comment]
Windows 10 22H2
Python v.3.6.8

PyCharm 2024.3.5 (Community Edition) (optional)))

| Package    | Version    | 
| --- | --- | 
| Keras-Applications | 1.0.8 | 
| Keras-Preprocessing | 1.1.2 |
| Markdown | 3.3.7 |
| Pillow | 8.4.0 |
| PyYAML | 6.0.1 | 
| Werkzeug | 2.0.3 | 
| absl-py | 1.4.0 |
| astor | 0.8.1 |
| cached-property | 2.0 |
| cycler | 0.11.0 | 
| dataclasses | 0.8 |
| easydict | 1.13 |
| gast | 0.6.0 |
| grpcio | 1.48.2 |
| h5py | 3.1.0 |
| importlib-metadata | 4.8.3 |
| kiwisolver | 1.3.1 |
| matplotlib | 3.3.4 |
| numpy | 1.19.5 |
| opencv-python | 3.4.0.12 |
| pip | 18.1 |
| protobuf | 3.19.6 | 
| pyparsing | 3.1.4 |
| python-dateutil | 2.9.0.post0 |
| scipy | 1.5.4 |
| setuptools | 40.6.2 |
| six | 1.17.0 |
| tensorboard | 1.12.2 | 
| tensorflow | 1.12.0 |
| termcolor | 1.1.0 | 
| toposort | 1.10 |
| typing-extensions | 4.1.1 |
| vtk | 9.3.1 |
| wheel | 0.37.1 |
| zipp | 3.6.0 | 

No problems - the flight is normal.
