### ISSUE TITLE
kitti.ckpt does not support global mode

### ISSUE THREAD

**Issue by weihaosky** [princeton-vl/DeepV2D#39]
Hi, when I use `kitti.ckpt` and set `--mode=global`, the following error arises:
```
Traceback (most recent call last):
  File "demos/demo_v2d.py", line 84, in <module>
    main(args)
  File "demos/demo_v2d.py", line 66, in main
    depths, poses = deepv2d(images, intrinsics, viz=True, iters=args.n_iters)
  File "deepv2d/deepv2d.py", line 467, in __call__
    self.update_poses(i)
  File "deepv2d/deepv2d.py", line 368, in update_poses
    self.poses, self.intrinsics, self.weights = self.sess.run(outputs, feed_dict=feed_dict)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 192, 1088) for Tensor 'Placeholder_1:0', which has shape '(5, 192, 1088)'
```
The `nyu.ckpt` is normal in both global and keyframe mode.

What is the problem?

Many thanks.

**Comment by shaiSchneider** [comment]
got the same problem, @weihaosky  did you manage to solve it?
